"""Short profiling smoke for Anima full-finetune cache modes.

Runs route/runtime jobs on the same tiny sample:
- cache_first with copied prebuilt cache
- online_cache cold start with only raw image/caption
- online_cache hot start reusing the cache generated by the cold run

The script samples process RSS and NVIDIA memory while entry_train.py runs.
It is intentionally a smoke/profiling helper, not a production entrypoint.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
import time
import argparse
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

if __package__ in (None, ""):
    project_root = Path(__file__).resolve().parents[3]
    backend_root = project_root / "backend"
    for item in (project_root, backend_root):
        if str(item) not in sys.path:
            sys.path.insert(0, str(item))

import psutil

from backend.core.lulynx_trainer.run_manifest import manifest_path_for
from backend.lulynx_launcher.services.training_registry import LulynxTrainingRegistry
from backend.lulynx_launcher.services.training_route_service import TrainingRouteService

IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png", ".webp"}

def _read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))

def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True), encoding="utf-8")


def _tail(path: Path, limit: int = 5000) -> str:
    if not path.is_file():
        return ""
    text = path.read_text(encoding="utf-8", errors="ignore")
    return text if len(text) <= limit else text[-limit:]


def _read_step_wall_profile(run_dir: Path) -> dict[str, Any]:
    events_path = run_dir / "events.jsonl"
    values: list[float] = []
    if not events_path.is_file():
        return {"count": 0, "values": []}
    for line in events_path.read_text(encoding="utf-8", errors="ignore").splitlines():
        try:
            event = json.loads(line)
        except json.JSONDecodeError:
            continue
        if event.get("event_type") != "step":
            continue
        data = event.get("data") if isinstance(event.get("data"), dict) else {}
        if "step_wall_seconds" not in data:
            continue
        try:
            values.append(float(data["step_wall_seconds"]))
        except (TypeError, ValueError):
            continue
    if not values:
        return {"count": 0, "values": []}
    after_first = values[1:]
    return {
        "count": len(values),
        "values": [round(v, 6) for v in values],
        "first_seconds": round(values[0], 6),
        "avg_seconds": round(sum(values) / len(values), 6),
        "avg_after_first_seconds": round(sum(after_first) / len(after_first), 6) if after_first else None,
        "min_seconds": round(min(values), 6),
        "max_seconds": round(max(values), 6),
    }


def _manifest_extra(manifest: dict[str, Any]) -> dict[str, Any]:
    extra = manifest.get("extra")
    return dict(extra) if isinstance(extra, dict) else {}


def _copy_raw_pair(source_dir: Path, target_dir: Path) -> Path:
    target_dir.mkdir(parents=True, exist_ok=True)
    for image_path in sorted(source_dir.iterdir()):
        if image_path.suffix.lower() not in IMAGE_SUFFIXES:
            continue
        caption_path = image_path.with_suffix(".txt")
        if not caption_path.is_file():
            continue
        shutil.copy2(image_path, target_dir / image_path.name)
        shutil.copy2(caption_path, target_dir / caption_path.name)
        return target_dir / image_path.name
    raise FileNotFoundError(f"No raw image/caption pair found under {source_dir}")


def _copy_cached_pair(source_dir: Path, target_dir: Path) -> Path:
    image_path = _copy_raw_pair(source_dir, target_dir)
    stem = image_path.stem
    text_cache = source_dir / f"{stem}_anima_te.npz"
    latent_caches = sorted(source_dir.glob(f"{stem}_*_anima.npz"))
    if not text_cache.is_file() or not latent_caches:
        raise FileNotFoundError(f"Missing cached Anima pair for {stem} under {source_dir}")
    shutil.copy2(text_cache, target_dir / text_cache.name)
    shutil.copy2(latent_caches[0], target_dir / latent_caches[0].name)
    return image_path


def _run_nvidia_smi(args: list[str]) -> str:
    try:
        result = subprocess.run(
            ["nvidia-smi", *args],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            timeout=4,
        )
    except Exception:
        return ""
    return result.stdout if result.returncode == 0 else ""


def _gpu_memory_sample(target_pids: set[int]) -> dict[str, float | None]:
    gpu_used = None
    gpu_total = None
    out = _run_nvidia_smi(["--query-gpu=memory.used,memory.total", "--format=csv,noheader,nounits"])
    if out.strip():
        first = out.strip().splitlines()[0]
        parts = [part.strip() for part in first.split(",")]
        if len(parts) >= 2:
            try:
                gpu_used = float(parts[0])
                gpu_total = float(parts[1])
            except ValueError:
                pass

    target_used = 0.0
    target_seen = False
    apps = _run_nvidia_smi(["--query-compute-apps=pid,used_memory", "--format=csv,noheader,nounits"])
    for line in apps.splitlines():
        parts = [part.strip() for part in line.split(",")]
        if len(parts) < 2:
            continue
        try:
            pid = int(parts[0])
            used = float(parts[1])
        except ValueError:
            continue
        if pid in target_pids:
            target_seen = True
            target_used += used
    return {
        "gpu_used_mb": gpu_used,
        "gpu_total_mb": gpu_total,
        "target_gpu_used_mb": target_used if target_seen else None,
    }


@dataclass
class ResourceProfile:
    elapsed_seconds: float
    samples: int
    peak_process_rss_mb: float
    peak_system_used_mb: float
    peak_gpu_used_mb: float | None
    peak_target_gpu_used_mb: float | None
    gpu_total_mb: float | None


class ProcessSampler:
    def __init__(self, pid: int, interval: float = 1.0):
        self.pid = pid
        self.interval = interval
        self.samples: list[dict[str, float | None]] = []
        self.started = time.perf_counter()

    def _target_pids(self) -> set[int]:
        pids = {self.pid}
        try:
            proc = psutil.Process(self.pid)
            pids.update(child.pid for child in proc.children(recursive=True))
        except psutil.Error:
            pass
        return pids

    def sample(self) -> None:
        rss = 0.0
        target_pids = self._target_pids()
        for pid in list(target_pids):
            try:
                rss += psutil.Process(pid).memory_info().rss / (1024 * 1024)
            except psutil.Error:
                continue
        vm = psutil.virtual_memory()
        gpu = _gpu_memory_sample(target_pids)
        self.samples.append(
            {
                "t": time.perf_counter() - self.started,
                "process_rss_mb": rss,
                "system_used_mb": vm.used / (1024 * 1024),
                **gpu,
            }
        )

    def wait(self, proc: subprocess.Popen[Any]) -> int:
        while proc.poll() is None:
            self.sample()
            time.sleep(self.interval)
        self.sample()
        return int(proc.returncode or 0)

    def profile(self) -> ResourceProfile:
        def max_present(key: str) -> float | None:
            values = [float(s[key]) for s in self.samples if s.get(key) is not None]
            return max(values) if values else None

        return ResourceProfile(
            elapsed_seconds=time.perf_counter() - self.started,
            samples=len(self.samples),
            peak_process_rss_mb=max(float(s.get("process_rss_mb") or 0.0) for s in self.samples),
            peak_system_used_mb=max(float(s.get("system_used_mb") or 0.0) for s in self.samples),
            peak_gpu_used_mb=max_present("gpu_used_mb"),
            peak_target_gpu_used_mb=max_present("target_gpu_used_mb"),
            gpu_total_mb=max_present("gpu_total_mb"),
        )


class ProfileRunner:
    def __init__(self, repo_root: Path):
        self.repo_root = repo_root
        self.backend_root = repo_root / "backend"
        self.registry = LulynxTrainingRegistry.default()
        self.schema = self.registry.get_by_id("anima-finetune")
        if self.schema is None:
            raise RuntimeError("anima-finetune schema is not registered")
        self.route_service = TrainingRouteService(self.repo_root, self.backend_root)
        self.route = self.route_service.resolve("anima-finetune")
        if not self.route.is_known:
            raise RuntimeError("anima-finetune route is not known")
        self.model_path = repo_root / "models" / "anima" / "diffusion_models" / "anima-preview2.safetensors"
        self.qwen3_path = repo_root / "models" / "anima" / "text_encoders" / "qwen_3_06b_base.safetensors"
        self.vae_path = repo_root / "models" / "anima" / "vae" / "qwen_image_vae.safetensors"
        for path in (self.model_path, self.qwen3_path, self.vae_path):
            if not path.is_file():
                raise FileNotFoundError(path)

    def build_config(
        self,
        name: str,
        data_dir: Path,
        output_dir: Path,
        mode: str,
        *,
        include_builder: bool,
        train_steps: int,
        block_checkpointing: bool,
        residency: str,
        native_block_count: int,
        prefetch: bool,
        prefetch_depth: int,
        prefetch_mode: str,
        pcie_transfer_format: str,
        sparse_swap: bool,
        optimizer_type: str,
        optimizer_args: str,
        gradient_release_mode: str,
        optimizer_state_paging: bool,
        activation_compression: bool,
        activation_compression_dtype: str,
        progressive_schedule: str,
        rematerial_profile: bool,
    ) -> dict[str, Any]:
        train_steps = max(int(train_steps or 1), 1)
        values: dict[str, Any] = {
            "pretrained_model": str(self.model_path),
            "output_name": f"lulynx_anima_full_finetune_{name}",
            "logging_dir": str(output_dir / "logs"),
            "device": "cuda",
            "mixed_precision": "bf16",
            "optimizer_type": str(optimizer_type or "AdamW"),
            "optimizer_backend": "torch_adamw",
            "optimizer_args": str(optimizer_args or ""),
            "learning_rate": 1e-6,
            "weight_decay": 0.0,
            "max_train_epochs": train_steps,
            "max_train_steps": train_steps,
            "train_batch_size": 1,
            "gradient_accumulation_steps": 1,
            "gradient_checkpointing": False,
            "anima_block_checkpointing": bool(block_checkpointing),
            "anima_block_residency": residency,
            "anima_block_prefetch": bool(prefetch),
            "anima_block_prefetch_depth": max(int(prefetch_depth or 1), 0),
            "anima_block_prefetch_mode": str(prefetch_mode or "original"),
            "pcie_transfer_format": str(pcie_transfer_format or "off"),
            "sparse_swap_enabled": bool(sparse_swap),
            "sparse_swap_warm_fraction": 0.35,
            "gradient_release_enabled": bool(gradient_release_mode and gradient_release_mode != "off"),
            "gradient_release_mode": str(gradient_release_mode or "post_step"),
            "optimizer_state_paging_enabled": bool(optimizer_state_paging),
            "optimizer_state_paging_min_tensor_mb": 0.0,
            "activation_compression_enabled": bool(activation_compression),
            "activation_compression_dtype": str(activation_compression_dtype or "fp16"),
            "activation_compression_min_tensor_mb": 0.0,
            "anima_progressive_full_finetune_enabled": bool(progressive_schedule),
            "anima_progressive_full_finetune_schedule": str(progressive_schedule or ""),
            "anima_rematerializable_block_enabled": bool(rematerial_profile),
            "anima_rematerializable_block_mode": "profile_only",
            "vram_auto_enhance_enabled": False,
            "native_cache_mode": mode,
            "anima_cached_training": True,
            "anima_native_block_count": max(int(native_block_count or 1), 1),
            "anima_qwen3_max_token_length": 16,
            "anima_text_token_limit": 16,
            "anima_cached_text_token_limit": 16,
            "anima_cached_latent_crop_size": 4,
            "native_runtime_profile": "standard",
            "torch_compile": False,
            "compile_runtime": "off",
            "compile_probe_enabled": False,
            "enable_fixed_token_padding": False,
            "cached_dataloader_workers": 0,
            "cached_dataloader_pin_memory": False,
            "pin_memory": False,
            "dataloader_num_workers": 0,
            "save_every_n_epochs": max(train_steps + 1, 999),
            "save_model_as": "safetensors",
            "no_metadata": False,
        }
        if include_builder:
            values.update({"qwen3": str(self.qwen3_path), "vae": str(self.vae_path)})
        config = self.route_service.build_config_json(
            schema=self.schema,
            route=self.route,
            config_values=values,
            output_dir=str(output_dir),
            train_data_dir=str(data_dir),
        )
        config["execution_profile_id"] = "flashattention-cache-profile-smoke"
        return config

    def run_case(
        self,
        *,
        name: str,
        data_dir: Path,
        output_dir: Path,
        mode: str,
        include_builder: bool,
        train_steps: int,
        block_checkpointing: bool,
        residency: str,
        native_block_count: int,
        prefetch: bool,
        prefetch_depth: int,
        prefetch_mode: str,
        pcie_transfer_format: str,
        sparse_swap: bool,
        optimizer_type: str,
        optimizer_args: str,
        gradient_release_mode: str,
        optimizer_state_paging: bool,
        activation_compression: bool,
        activation_compression_dtype: str,
        progressive_schedule: str,
        rematerial_profile: bool,
    ) -> dict[str, Any]:
        run_id = f"anima-cache-profile-{name}-{int(time.time() * 1000)}"
        config = self.build_config(
            name,
            data_dir,
            output_dir,
            mode,
            include_builder=include_builder,
            train_steps=train_steps,
            block_checkpointing=block_checkpointing,
            residency=residency,
            native_block_count=native_block_count,
            prefetch=prefetch,
            prefetch_depth=prefetch_depth,
            prefetch_mode=prefetch_mode,
            pcie_transfer_format=pcie_transfer_format,
            sparse_swap=sparse_swap,
            optimizer_type=optimizer_type,
            optimizer_args=optimizer_args,
            gradient_release_mode=gradient_release_mode,
            optimizer_state_paging=optimizer_state_paging,
            activation_compression=activation_compression,
            activation_compression_dtype=activation_compression_dtype,
            progressive_schedule=progressive_schedule,
            rematerial_profile=rematerial_profile,
        )
        run_dir = self.route_service.create_run_dir(
            run_id=run_id,
            schema_id="anima-finetune",
            route=self.route,
            runtime_id="flashattention-cache-profile-smoke",
            config_json=config,
            command=[sys.executable, "-u", "core/entry_train.py", "--config", "<run_dir>/config.json"],
            output_dir=str(output_dir),
        )
        _write_json(run_dir / "resolved_execution.json", {"execution_profile_id": "flashattention-cache-profile-smoke"})
        stdout_path = run_dir / "worker_stdout.log"
        stderr_path = run_dir / "worker_stderr.log"
        entry_script = self.backend_root / self.route.entry_script
        with stdout_path.open("w", encoding="utf-8") as out, stderr_path.open("w", encoding="utf-8") as err:
            proc = subprocess.Popen(
                [sys.executable, "-u", str(entry_script), "--config", str(run_dir / "config.json")],
                cwd=str(self.backend_root),
                stdout=out,
                stderr=err,
                text=True,
            )
            sampler = ProcessSampler(proc.pid, interval=1.0)
            rc = sampler.wait(proc)
        profile = sampler.profile()
        state_path = run_dir / "state.json"
        state = _read_json(state_path) if state_path.is_file() else {}
        manifest_path = manifest_path_for(output_dir)
        manifest = _read_json(manifest_path) if manifest_path.is_file() else {}
        manifest_extra = _manifest_extra(manifest)
        latent_caches = sorted(data_dir.glob("*_anima.npz"))
        text_caches = sorted(data_dir.glob("*_anima_te.npz"))
        ok = rc == 0 and state.get("status") == "completed" and int(state.get("current_step") or 0) >= train_steps
        result = {
            "name": name,
            "ok": ok,
            "run_id": run_id,
            "run_dir": str(run_dir),
            "output_dir": str(output_dir),
            "data_dir": str(data_dir),
            "returncode": rc,
            "state_status": state.get("status"),
            "step": int(state.get("current_step") or 0),
            "loss": state.get("last_loss"),
            "cache_files": {"latent": len(latent_caches), "text": len(text_caches)},
            "generated_cache_bytes": sum(p.stat().st_size for p in [*latent_caches, *text_caches]),
            "manifest_status": manifest.get("status"),
            "profile": profile.__dict__,
            "step_wall_profile": _read_step_wall_profile(run_dir),
            "anima_block_residency": manifest_extra.get("anima_block_residency", {}),
            "anima_block_checkpointing": manifest_extra.get("anima_block_checkpointing", {}),
            "anima_full_finetune_experiments": manifest_extra.get("anima_full_finetune_experiments", {}),
            "runtime_phase_timings": manifest_extra.get("runtime_phase_timings", {}),
            "stdout_tail": _tail(stdout_path, 3000) if not ok else "",
            "stderr_tail": _tail(stderr_path, 3000) if not ok else "",
        }
        _write_json(run_dir / "cache_profile_case_summary.json", result)
        self.route_service.update_run_status(run_id, "completed" if ok else "failed", exit_code=rc)
        return result


def main() -> int:
    parser = argparse.ArgumentParser(description="Profile Anima full-finetune cache modes.")
    parser.add_argument("--steps", type=int, default=1, help="optimizer steps per case")
    parser.add_argument(
        "--block-checkpointing",
        action="store_true",
        help="enable Anima DiT block checkpointing for all cases",
    )
    parser.add_argument(
        "--cases",
        default="cache_first,online_cold,online_hot",
        help="comma-separated case names: cache_first, online_cold, online_hot",
    )
    parser.add_argument(
        "--residency",
        default="resident",
        choices=("resident", "streaming_offload", "block_cpu_pinned"),
        help="Anima DiT block residency mode",
    )
    parser.add_argument("--native-block-count", type=int, default=1, help="number of native Anima DiT blocks to load")
    parser.add_argument("--prefetch", action="store_true", help="enable Anima streaming prefetch")
    parser.add_argument("--prefetch-depth", type=int, default=1, help="Anima streaming prefetch depth")
    parser.add_argument("--prefetch-mode", default="original", choices=("original", "adaptive"), help="Anima streaming prefetch policy")
    parser.add_argument("--pcie-transfer-format", default="off", help="experimental PCIe transfer format")
    parser.add_argument("--sparse-swap", action="store_true", help="enable sparse swap planning")
    parser.add_argument("--optimizer-type", default="AdamW", help="optimizer type, e.g. AdamW or AnimaFactoredAdamW")
    parser.add_argument("--optimizer-args", default="", help="optimizer args passed through config adapter")
    parser.add_argument(
        "--gradient-release-mode",
        default="off",
        choices=("off", "post_step", "during_backward"),
        help="enable gradient release in the selected mode",
    )
    parser.add_argument("--optimizer-state-paging", action="store_true", help="enable optimizer-state paging wrapper")
    parser.add_argument("--activation-compression", action="store_true", help="enable saved activation compression")
    parser.add_argument("--activation-compression-dtype", default="fp16", help="activation compression storage dtype")
    parser.add_argument("--progressive-schedule", default="", help="Anima progressive full-finetune schedule")
    parser.add_argument("--rematerial-profile", action="store_true", help="record rematerializable-block profile-only marker")
    args = parser.parse_args()
    train_steps = max(int(args.steps or 1), 1)
    selected_cases = [item.strip() for item in str(args.cases or "").split(",") if item.strip()]
    valid_cases = {"cache_first", "online_cold", "online_hot"}
    unknown_cases = [item for item in selected_cases if item not in valid_cases]
    if unknown_cases:
        raise ValueError(f"Unknown case(s): {', '.join(unknown_cases)}")

    repo_root = Path(__file__).resolve().parents[3]
    source_dir = repo_root / "sucai" / "6_lulu"
    if not source_dir.is_dir():
        raise FileNotFoundError(source_dir)
    profile_id = f"anima-cache-profile-{int(time.time() * 1000)}"
    profile_root = repo_root / "backend" / "tmp" / "anima_cache_profile" / profile_id
    profile_root.mkdir(parents=True, exist_ok=True)

    cache_first_data = profile_root / "cache_first_data"
    online_data = profile_root / "online_shared_data"
    _copy_cached_pair(source_dir, cache_first_data)
    _copy_raw_pair(source_dir, online_data)

    runner = ProfileRunner(repo_root)
    available_cases = [
        ("cache_first", cache_first_data, "cache_first", False),
        ("online_cold", online_data, "online_cache", True),
        ("online_hot", online_data, "online_cache", True),
    ]
    cases = [case for case in available_cases if case[0] in selected_cases]
    results = []
    for name, data_dir, mode, include_builder in cases:
        print(f"[profile] running {name}...")
        result = runner.run_case(
            name=name,
            data_dir=data_dir,
            output_dir=profile_root / name,
            mode=mode,
            include_builder=include_builder,
            train_steps=train_steps,
            block_checkpointing=bool(args.block_checkpointing),
            residency=str(args.residency),
            native_block_count=int(args.native_block_count or 1),
            prefetch=bool(args.prefetch),
            prefetch_depth=int(args.prefetch_depth or 1),
            prefetch_mode=str(args.prefetch_mode or "original"),
            pcie_transfer_format=str(args.pcie_transfer_format or "off"),
            sparse_swap=bool(args.sparse_swap),
            optimizer_type=str(args.optimizer_type or "AdamW"),
            optimizer_args=str(args.optimizer_args or ""),
            gradient_release_mode=str(args.gradient_release_mode or "off"),
            optimizer_state_paging=bool(args.optimizer_state_paging),
            activation_compression=bool(args.activation_compression),
            activation_compression_dtype=str(args.activation_compression_dtype or "fp16"),
            progressive_schedule=str(args.progressive_schedule or ""),
            rematerial_profile=bool(args.rematerial_profile),
        )
        results.append(result)
        print(
            f"[profile] {name}: ok={result['ok']} elapsed={result['profile']['elapsed_seconds']:.1f}s "
            f"gpu_peak={result['profile']['peak_gpu_used_mb']}MB rss_peak={result['profile']['peak_process_rss_mb']:.1f}MB "
            f"step_avg={result['step_wall_profile'].get('avg_seconds')}s "
            f"active_linear={result['anima_block_residency'].get('active_linear_count')}"
        )
        if not result["ok"]:
            _write_json(profile_root / "cache_profile_summary.json", {"status": "failed", "results": results})
            return 1

    summary = {
        "status": "passed",
        "profile_id": profile_id,
        "profile_root": str(profile_root),
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "steps_per_case": train_steps,
        "block_checkpointing": bool(args.block_checkpointing),
        "residency": str(args.residency),
        "native_block_count": int(args.native_block_count or 1),
        "prefetch": bool(args.prefetch),
        "prefetch_depth": int(args.prefetch_depth or 1),
        "prefetch_mode": str(args.prefetch_mode or "original"),
        "pcie_transfer_format": str(args.pcie_transfer_format or "off"),
        "sparse_swap": bool(args.sparse_swap),
        "optimizer_type": str(args.optimizer_type or "AdamW"),
        "optimizer_args": str(args.optimizer_args or ""),
        "gradient_release_mode": str(args.gradient_release_mode or "off"),
        "optimizer_state_paging": bool(args.optimizer_state_paging),
        "activation_compression": bool(args.activation_compression),
        "activation_compression_dtype": str(args.activation_compression_dtype or "fp16"),
        "progressive_schedule": str(args.progressive_schedule or ""),
        "rematerial_profile": bool(args.rematerial_profile),
        "notes": [
            "GPU shared-memory counters are not exposed by this smoke; use Windows GPUView/PerfMon for shared GPU memory.",
            "This is a one-block smoke for relative cold/hot overhead, not a full-quality benchmark.",
        ],
        "results": results,
    }
    _write_json(profile_root / "cache_profile_summary.json", summary)
    print(f"[profile] summary={profile_root / 'cache_profile_summary.json'}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
