# Auto-generated by export_molab_sdxl_repo.py. Do not edit by hand.
# Redirect `backend.<name>` imports to the top-level `<name>` module so the
# flattened molab export (backend/core -> core) keeps working with code that
# still does `from backend.core... import ...`. Both names share one object.
from __future__ import annotations

import importlib
import importlib.abc
import importlib.util
import sys

_PREFIX = "backend."


class _BackendAliasFinder(importlib.abc.MetaPathFinder, importlib.abc.Loader):
    def find_spec(self, fullname, path=None, target=None):
        if not fullname.startswith(_PREFIX):
            return None
        return importlib.util.spec_from_loader(fullname, self)

    def create_module(self, spec):
        module = importlib.import_module(spec.name[len(_PREFIX):])
        sys.modules[spec.name] = module
        return module

    def exec_module(self, module):
        return None


if not any(isinstance(f, _BackendAliasFinder) for f in sys.meta_path):
    sys.meta_path.insert(0, _BackendAliasFinder())
