#!/usr/bin/env python3
"""Export a standalone SDXL LoRA molab repository from the full Lulynx tree.

Run from the original repository root:
    python molab_sdxl_trainer/scripts/export_molab_sdxl_repo.py --out dist/lulynx-sdxl-molab
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SCAFFOLD = ROOT / "molab_sdxl_trainer"

EXCLUDED_DIRS = {
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "tests",
    "docs",
    "examples",
    "devtools",
    "data",
}
# NOTE: core/warehouse 不能排除。config_adapter.py 依赖
# `core.warehouse.training_features.flux_preflight`，是 entry_train 的硬依赖；
# 排除后运行会报 "No module named 'core.warehouse'"。

EXCLUDED_SUFFIXES = {
    ".pyc",
    ".pyo",
}

# Compatibility shim written to the export root as `backend/__init__.py`.
# The export flattens `backend/core` to a top-level `core` package, but many
# runtime modules still import `from backend.core... import ...`. This shim
# registers a meta-path finder that redirects any `backend.<name>` import to the
# matching top-level `<name>` module, so both import styles resolve to the very
# same module objects (no duplicate singletons).
BACKEND_SHIM = '''# Auto-generated by export_molab_sdxl_repo.py. Do not edit by hand.
# Redirect `backend.<name>` imports to the top-level `<name>` module so the
# flattened molab export (backend/core -> core) keeps working with code that
# still does `from backend.core... import ...`. Both names share one object.
from __future__ import annotations

import importlib
import importlib.abc
import importlib.util
import sys

_PREFIX = "backend."


class _BackendAliasFinder(importlib.abc.MetaPathFinder, importlib.abc.Loader):
    def find_spec(self, fullname, path=None, target=None):
        if not fullname.startswith(_PREFIX):
            return None
        return importlib.util.spec_from_loader(fullname, self)

    def create_module(self, spec):
        module = importlib.import_module(spec.name[len(_PREFIX):])
        sys.modules[spec.name] = module
        return module

    def exec_module(self, module):
        return None


if not any(isinstance(f, _BackendAliasFinder) for f in sys.meta_path):
    sys.meta_path.insert(0, _BackendAliasFinder())
'''


def _ignore_runtime(dir_path: str, names: list[str]) -> set[str]:
    ignored: set[str] = set()
    for name in names:
        path = Path(dir_path) / name
        if name in EXCLUDED_DIRS:
            ignored.add(name)
            continue
        if path.suffix in EXCLUDED_SUFFIXES:
            ignored.add(name)
            continue
        if name.endswith(".log") or name.endswith(".tmp"):
            ignored.add(name)
            continue
    return ignored


def _copytree(src: Path, dst: Path) -> None:
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst, ignore=_ignore_runtime)


def _copy_file(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


def export(out: Path) -> None:
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True, exist_ok=True)

    # Runtime core. Keep the whole core package for compatibility; SDXL LoRA is deeply coupled
    # to shared config/training/dataset/optimizer modules.
    _copytree(ROOT / "backend" / "core", out / "core")

    # The full repo keeps modules under `backend/core`; the export flattens that
    # to top-level `core`. Write a `backend` alias package so the many
    # `from backend.core... import ...` statements keep resolving, and make sure
    # the alias is registered before any core submodule imports it.
    backend_pkg = out / "backend"
    backend_pkg.mkdir(parents=True, exist_ok=True)
    (backend_pkg / "__init__.py").write_text(BACKEND_SHIM, encoding="utf-8")

    core_init = out / "core" / "__init__.py"
    if core_init.is_file():
        core_init_text = core_init.read_text(encoding="utf-8")
        if "import backend" not in core_init_text:
            core_init.write_text(
                "import backend  # noqa: F401,E402  molab flattened-export compat\n"
                + core_init_text,
                encoding="utf-8",
            )

    # Some core modules import the backend-root helper `project_roots` as a
    # bare top-level module (e.g. core/security.py). Ship it at the export root
    # so `from project_roots import ...` keeps resolving after the flatten.
    project_roots_src = ROOT / "backend" / "project_roots.py"
    if project_roots_src.is_file():
        _copy_file(project_roots_src, out / "project_roots.py")

    # Molab helper files.
    _copytree(SCAFFOLD / "configs", out / "configs")
    _copytree(SCAFFOLD / "notebooks", out / "notebooks")
    _copytree(SCAFFOLD / "scripts", out / "scripts")
    for req_name in (
        "requirements-molab.txt",
        "requirements-blackwell-cu128.txt",
        "requirements-sageattention.txt",
    ):
        src_req = SCAFFOLD / req_name
        if src_req.is_file():
            _copy_file(src_req, out / req_name)

    # Replace scaffold export script copy with a note? Keep it; useful for future refresh.
    readme = (SCAFFOLD / "README.md").read_text(encoding="utf-8")
    (out / "README.md").write_text(readme, encoding="utf-8")

    (out / "pyproject.toml").write_text(
        """[project]\nname = \"lulynx-sdxl-molab\"\nversion = \"0.1.0\"\ndescription = \"Standalone SDXL LoRA training subset exported from Lulynx Trainer for molab.\"\nrequires-python = \">=3.10\"\n\n[tool.setuptools.packages.find]\nwhere = [\".\"]\ninclude = [\"core*\", \"backend*\"]\n""",
        encoding="utf-8",
    )
    (out / ".gitignore").write_text(
        """__pycache__/\n*.py[cod]\n.venv/\n.env\nwork/models/\nwork/datasets/\nwork/outputs/\nwork/logs/\nwork/runs/\n*.safetensors\n*.ckpt\n*.pt\n*.pth\n""",
        encoding="utf-8",
    )
    for rel in ["work/models", "work/datasets", "work/outputs", "work/logs", "work/runs"]:
        (out / rel).mkdir(parents=True, exist_ok=True)
        (out / rel / ".gitkeep").write_text("", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Export standalone molab SDXL LoRA repo")
    parser.add_argument("--out", default="dist/lulynx-sdxl-molab", help="Output directory")
    args = parser.parse_args()
    out = Path(args.out)
    if not out.is_absolute():
        out = ROOT / out
    export(out)
    print(f"Exported molab SDXL LoRA repo to: {out}")
    print("Next:")
    print(f"  cd {out}")
    print("  git init && git add . && git commit -m 'Initial SDXL LoRA molab trainer'")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
